name: Go

on:
  workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build -o FT8Spy.exe ./src/FT8Spy/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: FT8Spy-Windows
        path: ./bin/FT8Spy.exe
